"""add description

Revision ID: 0423f30bc005
Revises: 
Create Date: 2026-04-22 03:11:47.563155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0423f30bc005'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('installments', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('installment_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('installment_number')
        batch_op.drop_column('installments')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
