"""add card transactions

Revision ID: 1d833b949ef0
Revises: 0423f30bc005
Create Date: 2026-04-22 05:04:22.614133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d833b949ef0'
down_revision = '0423f30bc005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('installments', sa.Integer(), nullable=True),
    sa.Column('installment_number', sa.Integer(), nullable=True),
    sa.Column('installment_value', sa.Float(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_transaction')
    # ### end Alembic commands ###
