"""add card transactions

Revision ID: 1d833b949ef0
Revises: 0423f30bc005
Create Date: 2026-04-22 05:04:22.614133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d833b949ef0'
down_revision = '0423f30bc005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
