"""add user name

Revision ID: 732fc3088fa9
Revises: 1d833b949ef0
Create Date: 2026-04-22 05:54:13.289938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732fc3088fa9'
down_revision = '1d833b949ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
