"""Adiciona campo symbol em Investment

Revision ID: dd485c1e459b
Revises: 732fc3088fa9
Create Date: 2026-04-30 06:57:05.287819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd485c1e459b'
down_revision = '732fc3088fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment', schema=None) as batch_op:
        batch_op.drop_column('symbol')

    # ### end Alembic commands ###
